name: SampleAppSwiftUI

configs:
  Development: debug
  Production: debug
  AppStore: release
  
options:
  bundleIdPrefix: com.adesso
  deploymentTarget:
    iOS: 17.0

attributes:
  BuildIndependentTargetsInParallel: YES

settings:
  ENABLE_USER_SCRIPT_SANDBOXING: false
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  SWIFT_EMIT_LOC_STRINGS: true
  
packages:
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    majorVersion: 3.8.0
  Pulse:
    url: https://github.com/kean/Pulse
    majorVersion: 3.0.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    majorVersion: 1.5.2

targets:
  SampleAppSwiftUI:
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
        product: CocoaLumberjackSwiftLogBackend
      - package: Pulse
        product: Pulse
        product: PulseUI
    configFiles:
        Development: SampleAppSwiftUI/Configs/Development.xcconfig
        Production: SampleAppSwiftUI/Configs/Production.xcconfig
        AppStore: SampleAppSwiftUI/Configs/AppStore.xcconfig
    type: application
    platform: iOS
    sources:
      - path: SampleAppSwiftUI
    scheme:
      testTargets:
      - SampleAppSwiftUITests
      - SampleAppSwiftUIUITests
    preBuildScripts:
        - path: scripts/installation/swiftlint.sh
          name: SwiftLint
          basedOnDependencyAnalysis: false
  SampleAppSwiftUITests:
    dependencies:
      - target: SampleAppSwiftUI
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
        product: CocoaLumberjackSwiftLogBackend
      - package: Pulse
        product: Pulse
        product: PulseUI
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SampleAppSwiftUITests
  SampleAppSwiftUIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SampleAppSwiftUIUITests
parallelizeBuild: true
