name: SampleAppSwiftUI

configs:
  Development: debug
  Production: debug
  AppStore: release
  
options:
  bundleIdPrefix: com.adesso
  deploymentTarget:
    iOS: 15.0

settings:
  enableBaseInternationalization: true
  
packages:
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    majorVersion: 3.8.0
  R.swift:
    url: https://github.com/mac-cain13/R.swift
    majorVersion: 7.2.4
  Pulse:
    url: https://github.com/kean/Pulse
    majorVersion: 3.0.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    majorVersion: 1.5.2

targets:
  SampleAppSwiftUI:
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: Pulse
        product: Pulse
        product: PulseUI
      - package: R.swift
        product: rswift
        product: RswiftLibrary
    configFiles:
        Development: SampleAppSwiftUI/Configs/Development.xcconfig
        Production: SampleAppSwiftUI/Configs/Production.xcconfig
        AppStore: SampleAppSwiftUI/Configs/AppStore.xcconfig
    type: application
    platform: iOS
    sources:
      - path: SampleAppSwiftUI
      - path: "SampleAppSwiftUI/Generated/R.generated.swift"
        optional: true
        type: file
    scheme:
      testTargets:
      - SampleAppSwiftUITests
      - SampleAppSwiftUIUITests
    preBuildScripts:
        - name: SwiftLint
          script: |
                  export PATH="$PATH:/opt/homebrew/bin"
                  if which swiftlint > /dev/null; then
                      swiftlint
                  else
                      echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                  fi
        - name: Generate Resources with R.swift
          script: |
                  "$SRCROOT/rswift" generate "$SRCROOT/R.generated.swift"
          inputFiles:
              - $TEMP_DIR/rswift-lastrun
          outputFiles:
              - $SRCROOT/$TARGET_NAME/Generated/R.generated.swift
  SampleAppSwiftUITests:
    dependencies:
      - target: SampleAppSwiftUI
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: Pulse
        product: Pulse
        product: PulseUI
      - package: R.swift
        product: rswift
        product: RswiftLibrary
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SampleAppSwiftUITests
  SampleAppSwiftUIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SampleAppSwiftUIUITests
