name: SampleAppSwiftUI

configs:
  Development: debug
  Production: debug
  AppStore: release
  
options:
  bundleIdPrefix: com.adesso
  deploymentTarget:
    iOS: 15.5

attributes:
  BuildIndependentTargetsInParallel: true

settings:
  enableBaseInternationalization: true
  
packages:
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    majorVersion: 3.8.0
  Pulse:
    url: https://github.com/kean/Pulse
    majorVersion: 3.0.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    majorVersion: 1.5.2

targets:
  SampleAppSwiftUI:
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: Pulse
        product: Pulse
        product: PulseUI
    configFiles:
        Development: SampleAppSwiftUI/Configs/Development.xcconfig
        Production: SampleAppSwiftUI/Configs/Production.xcconfig
        AppStore: SampleAppSwiftUI/Configs/AppStore.xcconfig
    type: application
    platform: iOS
    sources:
      - path: SampleAppSwiftUI
    scheme:
      testTargets:
      - SampleAppSwiftUITests
      - SampleAppSwiftUIUITests
    preBuildScripts:
        - path: scripts/installation/swiftlint.sh
          name: SwiftLint
          basedOnDependencyAnalysis: false
        - path: scripts/installation/swiftgen.sh
          name: SwiftGen
          basedOnDependencyAnalysis: false
  SampleAppSwiftUITests:
    dependencies:
      - target: SampleAppSwiftUI
      - package: CocoaLumberjack
        product: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: Pulse
        product: Pulse
        product: PulseUI
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SampleAppSwiftUITests
  SampleAppSwiftUIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SampleAppSwiftUIUITests
