name: SampleAppSwiftUI

configs:
  Development: debug
  Swifter: debug
  Production: debug
  AppStore: release
  
options:
  bundleIdPrefix: com.adesso
  deploymentTarget:
    iOS: 15.0

packages:
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    majorVersion: 3.8.0
  Swifter:
    url: https://github.com/httpswift/swifter
    exactVersion: 1.5.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    majorVersion: 1.5.2

targets:
  SampleAppSwiftUI:
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
    configFiles:
        Development: SampleAppSwiftUI/Configs/Development.xcconfig
        Production: SampleAppSwiftUI/Configs/Production.xcconfig
        Swifter: SampleAppSwiftUI/Configs/Development.xcconfig
        AppStore: SampleAppSwiftUI/Configs/AppStore.xcconfig
    type: application
    platform: iOS
    sources:
      - path: SampleAppSwiftUI
    scheme:
      testTargets:
      - SampleAppSwiftUITests
      - SampleAppSwiftUIUITests
      - Swifter
    preBuildScripts:
      - name: SwiftLint
        script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  Swifter:
    type: application
    platform: iOS
    sources:
      - path: SampleAppSwiftUI
  SampleAppSwiftUITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SampleAppSwiftUITests
  SampleAppSwiftUIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SampleAppSwiftUIUITests
