import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "SampleAppSwiftUI",
    projects: [
        Path.relativeToRoot("Projects/SampleAppSwiftUI")
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
