appId: com.adesso.SampleAppSwiftUI.development
onFlowStart:
  - maestro cloud --ios-version 16 SampleAppSwiftUI.app
---
- launchApp
- tapOn:
    id: "settingsTabView"
- tapOn: "0"
- assertVisible: "1"
