appId: com.adesso.SampleAppSwiftUI.development
onFlowStart:
  - maestro cloud --ios-version 16 SampleAppSwiftUI.app myflows/
---
- runFlow: settingsScreenDarkModeToggleTest.yaml
- runFlow: settingsScreenParitySelectionTest.yaml
