appId: com.adesso.SampleAppSwiftUI.development
onFlowStart:
  - maestro cloud --ios-version 16 SampleAppSwiftUI.app
---
- launchApp
- tapOn:
    id: "settingsTabView"
- tapOn:
    id: "settingsViewParitySelectionPicker"
- assertVisible:
    id: "settingsViewParitySelectionPickerCell"
- tapOn: "ETH"
- assertVisible: "ETH"
