name: iOS Build Check Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
            spec: project.yaml
            quiet: true
            version: '2.34.0'
      - name: Generate Project
        run: |
          xcodegen generate
      - name: Build
        run: |
          xcodebuild -scheme SampleAppSwiftUI clean build -sdk iphoneos -configuration Development CODE_SIGNING_ALLOWED=No
