name: iOS Build Check Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
env:
  APP_PATH: $(find . -name "*.app" | head -n 1)

jobs:
  build:
    name: Build scheme
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
            spec: project.yml
            quiet: true
            version: 'latest'
      - name: Generate Project
        run: |
          xcodegen generate
      - name: Build
        run: |
          xcodebuild -scheme SampleAppSwiftUI clean build -sdk iphoneos -configuration Development CODE_SIGNING_ALLOWED=No -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build
      - name: UI Test
        uses: mobile-dev-inc/action-maestro-cloud@v1.6.0
        with:
            api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
            app-file: build/SampleAppSwiftUI.app
            ios-version: 16
